/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_nlp_sempre_ComputationGraphWrapper */

#ifndef _Included_edu_stanford_nlp_sempre_ComputationGraphWrapper
#define _Included_edu_stanford_nlp_sempre_ComputationGraphWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_nlp_sempre_ComputationGraphWrapper
 * Method:    test
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_edu_stanford_nlp_sempre_ComputationGraphWrapper_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
