#!/bin/sh
# SEMPATH=../semparse
GRAMMAR=./shrdlurn/evenricher.grammar
EXAMPLEPATH=~/shrdlurn/examples/
NEWGRAMMARPATH=~/shrdlurn/grammar/
LOGPATH=~/shrdlurn/logs/
# cd $SEMPATH
PARSEROPTS='-Parser.pruneErrorValues true -Parser BeamParser -Parser.trackedCats $Color $Number $NumberSeq $Cond $CondSeq $Action $ActionSeq -FloatingParser.defaultIsFloating true'

# -FloatingParser.maxDepth 12 -FloatingParser.useSizeInsteadOfDepth true -FloatingParser.defaultIsFloating true -FloatingParser.useAnchorsOnce true"
LEARNOPTS="-Params.l1Reg lazy -Params.l1RegCoeff 0.001 -Parser.beamSize 50 -Params.initStepSize 0.1 -Params.adaptiveStepSize true -ParserState.customExpectedCounts UNIFORM"
FEATOPTS='-FeatureExtractor.featureComputers interactive.blocks.RicherStacksWorldFeatureComputer -FeatureExtractor.featureDomains rule subtree
-RicherStacksWorldFeatureComputer.ngramN 2 -RicherStacksWorldFeatureComputer.parameterizeCats $Number $Color'

OPTIONS="-Dmodules=core,interactive -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main
-execDir _OUTPATH_/runRichmoreparams -overwriteExecDir -addToView 0
-Main.interactive 
-JavaExecutor.convertNumberValues false
-JavaExecutor.classPathPrefix edu.stanford.nlp.sempre.interactive.blocks.RicherStacksWorld
-Params.initWeightsRandomly false
-Grammar.inPaths $GRAMMAR
-Grammar.binarizeRules false
-Grammar.useApplyFn interactive.ApplyFn
-LanguageAnalyzer.lowerCaseTokens true -LanguageAnalyzer.useLemmaTokens false"

# features are tree, heads, ngram
DEBUG="-Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=8898"
TRAIN_OUTS_LOCAL="-Master.newExamplesPath $EXAMPLEPATH -Master.logPath $LOGPATH -Master.newGrammarPath $NEWGRAMMARPATH"
INDEP_SESSIONS="-Master.onlineLearnExamples false -Master.independentSessions true"
SESSIONS="-Master.onlineLearnExamples true -Master.independentSessions false"

TRAIN_IN="-Dataset.inPaths def:./shrdlurn/sidaw.lisp -Learner.maxTrainIters 1"


echo "not running on jonsson"
rlwrap java $OPTIONS $PARSEROPTS $LEARNOPTS $FEATOPTS $SESSIONS $TRAIN_OUTS_LOCAL $TRAIN_IN -server true -Server.numThreads 8 $@
